spring.application.name=ecommerce
server.port=8080
spring.profiles.active=local

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update      
spring.jpa.show-sql=true       
spring.jpa.properties.hibernate.format_sql=true            

 # SSLCommerz Sandbox Credentials
sslcommerz.store-id=${SSLCOMMERZ_STORE_ID}
sslcommerz.store-password=${SSLCOMMERZ_STORE_PASSWORD}
sslcommerz.base-url=${SSLCOMMERZ_BASE_URL}
sslcommerz.init-url=${SSLCOMMERZ_INIT_URL}
sslcommerz.validation-url=${SSLCOMMERZ_VALIDATION_URL}

# Set to false for production
sslcommerz.sandbox=true